name: Create Comment when pull request approved or check run completed

on: 
  issue_comment:
  push:

jobs:
  create_comment:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: status
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: gh pr status

#       - name: comment
#       - uses: actions-ecosystem/action-create-comment@v1
# #         if: ${{ startsWith(github.event.comment.body, '/hello') }}
#         with:
#           github_token: ${{ secrets.github_token }}
#           body: |
#             Hello, @${{ github.actor }}!
