name: Merge PR v0.1

on: 
  issue_comment:
  #for debug only
#   push:

jobs:
  create_comment:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: guard for magic spell
        if: ${{ github.event.comment.body != 'release major'}}
        run: exit 1
      - uses: actions-ecosystem/action-create-comment@v1
        with:
          github_token: ${{ secrets.github_token }}
          body: |
            Hello, @${{ github.actor }}! Merging PR for command **${{ github.event.comment.body}}** for PR #**${{ github.event.issue.number }}**
      - name: Merge Pull Request 
        run: gh pr merge ${{ github.event.issue.number }} -s
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ''
          release_branches: 'develop'
