name: Merge PR v0.1

on: 
  issue_comment:
  #for debug only
  push:

jobs:
  create_comment:
    runs-on: ubuntu-latest
    steps:
      - name: guard for magic spell
        if: ${{ github.event.comment.body != 'release major'}}
        run: exit 1
      - name: checkout
        uses: actions/checkout@v2
      - uses: actions-ecosystem/action-create-comment@v1
        with:
          github_token: ${{ secrets.github_token }}
          body: |
            Hello, @${{ github.actor }}! Merging PR for major release            
      - name: Merge me!
        uses: ridedott/merge-me-action@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
