name: Create Comment when pull request approved or check run completed

on: 
  issue_comment:
  #for debug only
  push:

jobs:
  create_comment:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: actions-ecosystem/action-create-comment@v1
        if: ${{ github.event.comment.body == 'release major') }}
        with:
          github_token: ${{ secrets.github_token }}
          body: |
            Hello, @${{ github.actor }}!
