name: Create Comment when pull request approved or check run completed

on:
  push:
  pull_request_review:
    types: [submitted]

jobs:
  build:
#     if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
steps: 
    - uses: actions-ecosystem/action-create-comment@v1
      with:
        github_token: ${{ secrets.github_token }}
        body: |
          Hello, @${{ github.actor }}!
