name: Bump version
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Bump version and push tag, dry run to get the next tag
      uses: anothrNick/github-tag-action@1.26.0
      id: dry_run
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RELEASE_BRANCHES: develop
        DEFAULT_BUMP: patch
        DRY_RUN: true
        
    - name: update version.xcconfig
      run:
        echo "new tag:"
        echo ${{steps.dry_run.outputs.new_tag}}
