on:
  pull_request_review:
    types: [submitted]

jobs:
  comment:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps: 
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo ${{github.event }}
    - uses: actions-ecosystem/action-create-comment@v1
      with:
        github_token: ${{ secrets.github_token }}
        body: |
          Hello, @${{ github.actor }}! Thx for approved the PR!
