name: comment for review approval

on:
  pull_request_review:
    types: [submitted]

jobs:
  comment:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps: 
    - name: Dump GitHub context
      run: echo ${{ job }}
    - uses: actions-ecosystem/action-create-comment@v1
      with:
        github_token: ${{ secrets.github_token }}
        body: |
          Hello, @${{ github.actor }}! Thx for approved the PR! job detail: ${{ job }}
