on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v2
      - id: foo
        uses: billypchan/mergeSpell@1.1
        with:
          who-to-greet: 'Mona the Octocat'
          admins: ('billypchan', 'billchan2021')
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
