name: My action

on:
  workflow_dispatch:
  push:
    branches:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest
    env:
        JUICE: |
          [
            "apple-juice",
            "orange-juice"
          ]
        FRUIT: |
          [
            "apple",
            "orange"
          ]
        ADMINS: |
          ['billypchan',
          'marcoconti83',
          'typfel',
          'johnxnguyen',
          'David-Henner',
          'KaterinaWire'
          ]

    steps:
    - name: check juice
      if: contains(${{ env.JUICE }}, 'apple')
      run: |
        echo "Found Juice"

    - name: check mango
      if: ${{ contains(env.FRUIT, 'mango') }}
      run: |
        echo "Found mango"

    - name: check admins 1
      if: contains(env.ADMINS, 'billypchan')
      run: |
        echo "Found billypchan"


    - name: check admins 2
      if: ${{ contains(env.ADMINS, 'billy') }}
      run: |
        echo "Found billy"

    - name: check admins 3
      run: |
          for i in "${{ env.ADMINS }}"
          do
            echo $i
            if ["$i" == "billypchan"]; then
              echo "Found billypchan in 1"
              echo $i
            fi


          done
