name: My action

on:
  push:
    branches:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest
    env:
        JUICE: |
          [
            "apple-juice",
            "orange-juice"
          ]
        FRUIT: |
          [
            "apple",
            "orange"
          ]
        ADMINS: |
          ['billypchan',
          'marcoconti83',
          'typfel',
          'johnxnguyen',
          'David-Henner',
          'KaterinaWire'
          ]

    steps:
    - name: check juice
      if: contains(${{ env.JUICE }}, 'apple')
      run: |
        echo "Found Juice"

    - name: check juice full
      if: contains(${{ env.JUICE }}, 'apple-juice')
      run: |
        echo "Found Juice Full"

    - name: check fruit
      if: ${{ contains(env.FRUIT, 'apple') }}
      run: |
        echo "Found Fruit"

    - name: check mango
      if: ${{ contains(env.FRUIT, 'mango') }}
      run: |
        echo "Found mango"

    - name: check admins
      if: ${{ contains(env.ADMINS, 'billyphcan') }}
      run: |
        echo "Found billyphcan"


    - name: check admins
      if: ${{ contains(env.ADMINS, 'billy') }}
      run: |
        echo "Found billy"
