name: array check test

on:
  workflow_dispatch:
  push:
    branches:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest
    env:
        JUICE: |
          [
            "apple-juice",
            "orange-juice"
          ]
        FRUIT: |
          [
            "apple",
            "orange"
          ]
        ADMINS: ('billypchan' 'marcoconti83' 'typfel' 'johnxnguyen' 'David-Henner' 'KaterinaWire')

    steps:
    - name: check juice
      if: contains(${{ env.JUICE }}, 'apple')
      run: |
        echo "Found Juice"

    - name: check mango
      if: ${{ contains(env.FRUIT, 'mango') }}
      run: |
        echo "Found mango"

    - name: check admins 1
      if: contains(env.ADMINS, 'billypchan')
      run: |
        echo "Found billypchan"


    - name: check admins 2
      if: ${{ contains(env.ADMINS, 'billy') }}
      run: |
        echo "Found billy"

    - name: check admins 3
      run: |
          array=${{ env.ADMINS }}
          for i in ${array[*]}
          do
            admin=${array[$i]}
            echo $admin
            if [$admin == "billypchan"]; then
              echo "Found billypchan in 1"
              echo $i
            fi


          done
